version: 2.1
orbs:
  rn: react-native-community/react-native@4.4.2

jobs:
  analyse_js:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          command: yarn lint
          name: Run ESLint
      - run:
          command: yarn test
          name: Jest
  checkout_code:
    executor:
      name: rn/linux_js
      node_version: '10'
    steps:
      - checkout
      - run: 
          name: Copy .env.example to .env
          command: |
              cp .env.example .env
      - run: 
          name: Remove postinstall from package.json
          command: |
              grep -v '    "postinstall": "cd ios && pod install && cd .."' package.json > temp-package.json; mv temp-package.json package.json
      - persist_to_workspace:
          paths: .
          root: .

  # merge_master:
  #   executor: rn/linux_js
  #   steps:
  #     - attach_workspace:
  #         at: .
  #     - run: 
  #         name: Merge Master
  #         command: |
  #             mkdir ~/.ssh
  #             ssh-keyscan github.com >> ~/.ssh/known_hosts
  #             git config --global user.email "you@example.com"
  #             git config --global user.name "Your Name"
  #             mv .gitignore.master .gitignore
  #             git rm -r --cached .
  #             git checkout -b master
  #             git add . && git commit -m "Merge"
  #             git push origin master --force
  
  # fastlane_android_release:
  #   executor: rn/linux_js
  #   steps:
  #     - attach_workspace:
  #         at: .
  #     - rn/yarn_install
  #     - run:
  #         command: echo
  #         name: Run Fastlane
  # fastlane_ios_release:
  #   executor: rn/linux_js
  #   steps:
  #     - attach_workspace:
  #         at: .
  #     - rn/yarn_install
  #     - run:
  #         command: echo 1
  #         name: Run Fastlane

workflows:
  test:
    jobs:
      - checkout_code:
          filters:
            branches:
              ignore:
                - master
                - dev
      - analyse_js:
          requires:
            - checkout_code
          filters:
            branches:
              ignore:
                - master
                - dev
      # - merge_master:
      #     requires:
      #       - checkout_code
      #     filters:
      #       branches:
      #         only:
      #           - dev
      - rn/android_build:
          build_type: debug
          name: build_android_debug
          project_path: android
          requires:
            - analyse_js
          filters:
            branches:
              ignore:
                - dev
                - master
      - rn/android_build:
          build_type: release
          name: build_android_release
          project_path: android
          requires:
            - analyse_js
          filters:
            branches:
              ignore:
                - dev
                - master
      # - rn/android_test:
      #     detox_configuration: android.emu.release
      #     requires:
      #       - build_android_release
      #     filters:
      #       branches:
      #         ignore:
      #           - dev
      #           - master
      # - rn/ios_build:
      #     build_configuration: Release
      #     device: iPhone X
      #     name: build_ios_release
      #     node_version: '10'
      #     project_path: ios/Example.xcodeproj
      #     requires:
      #       - analyse_js
      #     scheme: Example
      #     filters:
      #       branches:
      #         ignore:
      #           - dev
      #           - master
      # - rn/ios_build_and_test:
      #     build_configuration: Release
      #     detox_configuration: ios.sim.release
      #     device: iPhone X
      #     node_version: '10'
      #     project_path: ios/Example.xcodeproj
      #     requires:
      #       - analyse_js
      #     scheme: Example
      #     filters:
      #       branches:
      #         ignore:
      #           - dev
      #           - master
      # - fastlane_android_release:
      #     requires:
      #       - rn/android_test
      #     filters:
      #       branches:
      #         ignore:
      #           - dev
      #           - master
      # - fastlane_ios_release:
      #     requires:
      #       - rn/ios_build_and_test
      #     filters:
      #       branches:
      #         ignore:
      #           - dev
      #           - master
