# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  # desc "Push a new beta build to TestFlight"
  # lane :beta do
  #   increment_build_number(xcodeproj: "CityAReal.xcodeproj")
  #   build_app(workspace: "CityAReal.xcworkspace", scheme: "CityAReal")
  #   upload_to_testflight
  # end

  desc "Push a new beta build to Firebase App Distribution"
  lane :beta do
    # update_project_provisioning(
    #   profile: "certs/demodevelopment.mobileprovision", # optional if you use sigh
    # )
    increment_build_number(xcodeproj: "AirTravel.xcodeproj")
    build_app(
      workspace: "AirTravel.xcworkspace",
      scheme: "AirTravel",
      export_options: {
        # Manual Signing
        # method: "development",
        # provisioningProfiles: { 
        #   "vn.com.citya" => "demo-development",
        # }

        # Auto Signing
        method: 'ad-hoc'
      }
    )
    
    firebase_app_distribution(
      app: "1:1023557421676:ios:dd6266ddbd67e036f72649",
      # testers: "vietlongle0599@gmail.com",
      firebase_cli_token: '1//0gUSGEfAwSzVRCgYIARAAGBASNwF-L9IrEiizOSPN57rCfWpZjR0IZMg41fYJkidS1zsRC9Va9bE2fDX_RL6yUHb_SFthARQXhtc',
      release_notes: "Lots of amazing new features to test out!",
      groups: "ios-tester"
    )
  end
end
