# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    # gradle(task: "clean assembleRelease")
    # crashlytics
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here

    firebase_app_distribution(
      app: "1:1023557421676:android:825f79d06d4825cbf72649",
      # testers: "vietlongle0599@gmail.com",
      firebase_cli_token: '1//0g270_blxCjABCgYIARAAGBASNwF-L9IrQWKrUgwD60NewF9gydgdIUuoRURxMgIkpY2H8-N4Z9byBnLW4fHBFOJHUx40dTyMfU0',
      release_notes: "Lots of amazing new features to test out!",
      groups: "android-tester"
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
